title: Orbit Sling
description: Clarity and predictability for your pipeline.
baseurl: "/new-orbit-sling-site"
url: "https://trevor-orbit-sling.github.io"
markdown: kramdown
permalink: pretty

# Disable Jekyll posts
collections: {}
